pipeline {
  agent any
triggers {
        cron('* * * * *')
    }
  stages {
    stage('Checkout') {
      steps {
        echo 'Checkout code'
      }
    }
        stage('Web') {
          steps {
            bat 'runWebTests.bat'
          }
        }
  }
  post {
    always {
      junit 'results/*.xml'

    }

  }
}
